# Generated by Django 2.1.5 on 2020-05-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_friend_friend_request_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
